// Code generated by ent, DO NOT EDIT.

package ent

import (
	"GoServer/ent/schema"
	"GoServer/ent/todos"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	todosFields := schema.Todos{}.Fields()
	_ = todosFields
	// todosDescTitle is the schema descriptor for title field.
	todosDescTitle := todosFields[1].Descriptor()
	// todos.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	todos.TitleValidator = todosDescTitle.Validators[0].(func(string) error)
	// todosDescCreatedAt is the schema descriptor for created_at field.
	todosDescCreatedAt := todosFields[3].Descriptor()
	// todos.DefaultCreatedAt holds the default value on creation for the created_at field.
	todos.DefaultCreatedAt = todosDescCreatedAt.Default.(func() time.Time)
	// todosDescUpdatedAt is the schema descriptor for updated_at field.
	todosDescUpdatedAt := todosFields[4].Descriptor()
	// todos.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	todos.DefaultUpdatedAt = todosDescUpdatedAt.Default.(func() time.Time)
	// todos.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	todos.UpdateDefaultUpdatedAt = todosDescUpdatedAt.UpdateDefault.(func() time.Time)
}
